name: CI/CD DevOps python App
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          
      - name: Build Docker image
        run: |
            echo "Building Docker image..."
            docker build -t my-python-app .
          

      #- name: Deploy to server
       # env:
       #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #  SSH_HOST: ${{ secrets.SSH_HOST }}
        #  SSH_USER: ${{ secrets.SSH_USER }}
        #run: |
        #  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        #  ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        #  scp -r . $SSH_USER@$SSH_HOST:/path/to/deploy/directory
        #  ssh $SSH_USER@$SSH_HOST 'cd /path/to/deploy/directory && ./deploy_script.sh'